# Generated by Django 3.1.7 on 2021-03-23 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_category', models.CharField(max_length=150)),
                ('query_question', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_query', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.query')),
            ],
        ),
    ]
