# Generated by Django 3.1.7 on 2021-03-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_answer_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id_ans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.query'),
        ),
    ]
