# Generated by Django 3.1.7 on 2021-03-25 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_answer_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nm', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('msg', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
